In [2]:
import torch
import numpy as np
print("Gpu enabled: " , torch.cuda.is_available())

Gpu enabled:  True


In [4]:
B = np.arange(24).reshape(2,3,4)
B

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [5]:
# 3.1 B has shape (2, 3, 4). What is the shape after B.reshape(4,6)?
B.reshape(4,6) # it would results in 4 rows 6 coloumns

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
# 3.2 What is the shape after B.reshape(-1)?

B.reshape(-1) # it flattens it to one dimension

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [7]:
# What is the shape after B.reshape(2,-1)?

B.reshape(2,-1) # it would results in seprate tensors but no inner dimensions means 2 vectors inside one tensor

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [10]:
# What is the shape of B.permute(2,0,1)?

# permute is used for moving dimensions like advanced version of transpose.
# B = torch.as_tensor(B)
# B.permute(2,0,1)

In [ ]:
# What is the shape of B.transpose(0,1) (swap axes 0 and1)?

B.transpose(1,2)
B.transpose(0,1)

tensor([[[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]],

        [[12, 16, 20],
         [13, 17, 21],
         [14, 18, 22],
         [15, 19, 23]]])

In [ ]:
# Given x of shape (1, 3, 1, 5), what is the shape after x.squeeze()?
X = torch.rand(1, 3, 1, 5)
X.squeeze().shape # it would be (3,5) as .squeeze() removes all dimensions that have size 1,


torch.Size([3, 5])

In [ ]:
# Given y of shape (3, 5), what is the shape after x.unsqueeze(1)?

Y = torch.rand(3, 5)
Y.unsqueeze(1).shape # it would be (3, 1, 5) as ,unsqueeze(index) inserts a new dimension at that index.

torch.Size([3, 1, 5])

In [ ]:
# Why does calling .view() sometimes raise a runtime error while .reshape() does not on the same tensor? 

# .view() only creates a new view of the same memory and requires the tensor to be contiguous.
# .reshape() tries to create a view first; if that is not possible because the tensor is non-contiguous, it creates a copy with new memory.

In [ ]:
# After y = B.permute(1,0,2), is y contiguous in memory? What must you call before you can safely .view() it?

y = B.permute(1,0,2)
y.is_contiguous() # results in FALSE
y = y.contiguous() # THIS HELPS IN STORING IT BACK TO CONTIGOUS MEMORY -> allocates new memorythe
y.is_contiguous() # results in TRUE

y.view(3,8) # now it would works


tensor([[ 0,  1,  2,  3, 12, 13, 14, 15],
        [ 4,  5,  6,  7, 16, 17, 18, 19],
        [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# What is the shape of B.flatten(start_dim=1)?

B.flatten(start_dim=1) # flattens the first dimension, works same as 

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [43]:
# Given x of shape (2, 3, 4, 5), what is the shape after x.transpose(1,3)?
 

TENSOR = torch.rand(2, 3, 4, 5)
TENSOR.transpose(1,3).shape # (2,5,4,3)

torch.Size([2, 5, 4, 3])

In [50]:
# What is the shape after torch.movedim(x, 0, -1) for x of shape (2, 3, 4)?

TENSOR_1 = torch.rand(2, 3, 4)
torch.movedim(TENSOR_1, 1, 1) # torch.movedim(input_tensor, source, destination)



tensor([[[0.1207, 0.9532, 0.3323, 0.9496],
         [0.3495, 0.8559, 0.1425, 0.7740],
         [0.6663, 0.1645, 0.9048, 0.9908]],

        [[0.4786, 0.0349, 0.6872, 0.7139],
         [0.0909, 0.4294, 0.0050, 0.0510],
         [0.1076, 0.7090, 0.9329, 0.6409]]])