In [2]:
import torch 
print(torch.cuda.is_available())

True


In [3]:
scalar = torch.tensor(1)
print(f"Scalar: {scalar}")

vector = torch.tensor([1,2,3])
print(f"Vector: {vector}")

matrix = torch.tensor([[1,2,3,4,5,6],[2,5,3,4,1,4]])
matrix_2 = torch.tensor([[1,2,3,4,5,6],[2,5,3,4,1,4]])
# matrix_2 = torch.tensor([[3,2], [4,5], [3,9], [2,6], [9,9], [8,7]])
print(f"Matrix: {matrix}")

Scalar: 1
Vector: tensor([1, 2, 3])
Matrix: tensor([[1, 2, 3, 4, 5, 6],
        [2, 5, 3, 4, 1, 4]])


In [4]:
print(matrix * matrix_2)

tensor([[ 1,  4,  9, 16, 25, 36],
        [ 4, 25,  9, 16,  1, 16]])


In [5]:
tensor_3 = torch.randn(2,2 , dtype=torch.float64)
tensor_4 = torch.randn(2,2, dtype=torch.float64)

print(tensor_3 * tensor_4)
tensor_3.dtype

tensor([[-0.8576, -0.0421],
        [-0.8890, -0.5822]], dtype=torch.float64)


torch.float64

In [6]:
vector_2 = torch.zeros(1000000)
# vector_2.new_empty(2)
vector_2

tensor([0., 0., 0.,  ..., 0., 0., 0.])