In [1]:
import torch
print("GPU enabled: ", torch.cuda.is_available())

GPU enabled:  True


In [2]:
x = torch.ones(2,3,3)
total_space = x.element_size() * x.numel()
total_space

72

In [3]:
# Pytorch have some properties that donot requried parenthesis (), means they are not computing anything, they are just returning the info they already know, in simple words 
# they are not functions right, where as the () one are functions not properties that calculate or do computization on tensor right. For example: tensor.add() , 
# tensor.sum(), tensor.element_size(), tensor.numel() etc

# Simple if any thing is in general stored in metadata of tensor, so its written not as method or function.

In [ ]:
a = torch.randint(0,10,(3,2))
print(a)
print(a[1,0]) # first index is for row and second is for coloumn
print(a[-1,0]) # here minus index indicates from bottom -1 = last row
print(a[:,0].reshape(3,1)) # print complete coloum
print(a[:,1]) # print second coloumn (first index) all rows
print(a[0,:]) # print first row (zero index) all coloumns OR simply a[0]


tensor([[1, 5],
        [0, 6],
        [3, 7]])
tensor(0)
tensor(3)
tensor([[1],
        [0],
        [3]])
tensor([5, 6, 7])
tensor([1, 5])


In [5]:
b = torch.arange(1,10)
print(b)
print(b[1:4]) # this is known as range slicing that means b[start_index:end_index] give me value from start_index to end_index

c = torch.arange(10,19).reshape(3,3)
print(c)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([2, 3, 4])
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])


In [ ]:
# at the end tensors indexing is used for selecting one specific element from any row/col a[0,2] = first row, second coloumn OR selecting any row complete a[3] or a[3,:] 
# means 4 row (3rd index) and all coloumns OR select only an coloumn using indexing.