In [17]:
import torch
print("Gpu enabled: ", torch.cuda.is_available())

Gpu enabled:  True


In [18]:
# in this notebook we are going to cover tensors slicing, previously we learn tensors indexing that was about selecting one complete row/coloumn OR any specific element 
# inside it. 

# Tensors slicing is used for selecting range of elements.

In [19]:
tensor_1 = torch.arange(1,65).reshape(8,8)
print(tensor_1)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])


In [20]:
# ":" this colon is used for slicing but syntax is a bit different compare with indexing. 

# start : stop : step (this how its works lets understand in bit deep)

# start -> where to begin
# stop -> where to stop
# step -> how many positions to move each time

# a[rows, coloumn] 

In [21]:
print(tensor_1)

print(" \n")
print("Start from second row (first index) and stop before 3rd row (till second row)")
print(tensor_1[1:3]) 

print(" \n")
print("Start from second row (skip first one)")
print(tensor_1[1:]) 

print(" \n")
print("Stop before 3rd row (second index)")
print(tensor_1[:2]) 

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])
 

Start from second row (first index) and stop before 3rd row (till second row)
tensor([[ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]])
 

Start from second row (skip first one)
tensor([[ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])
 

Stop before 3rd row (second index)
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16]])


In [22]:
print(tensor_1[:]) # complete row, cols
print(tensor_1[:,:2]) # this is index X slicing use means all rows and index 0,1 cols (stop before 2)

print(tensor_1[1:3])


tensor([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])
tensor([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26],
        [33, 34],
        [41, 42],
        [49, 50],
        [57, 58]])
tensor([[ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]])


In [23]:
# Slicing always operates on the dimension you're slicing, means it varies.

# In simple words vector slicing works based on elements 1:3 from 1 before 3 right but in 2d tensor it works like 0 means first row not element so 1:3 means from 
# 1 row before 3rd row

In [ ]:
print(tensor_1[::])
print(tensor_1[1:3,0:3]) # two rows, 3 coloumns
print(tensor_1[1:3,2:]) # two rows, start at coloumn 2 till end
print(tensor_1[::3]) # ::3 -> the number is integer it tells that move this integer way on every index so on.


tensor([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])
tensor([[ 9, 10, 11],
        [17, 18, 19]])
tensor([[11, 12, 13, 14, 15, 16],
        [19, 20, 21, 22, 23, 24]])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [25, 26, 27, 28, 29, 30, 31, 32],
        [49, 50, 51, 52, 53, 54, 55, 56]])


In [35]:
print(tensor_1[2:]) # from 2 onwards
print(tensor_1[:2]) # all before 
print(tensor_1[::])

tensor([[17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16]])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])


# pattern to understand

a[:]        # Select all rows (and all columns for a 2D tensor)
a[:2]       # Select rows before index 2 (rows 0 and 1)
a[2:]       # Select rows from index 2 onwards
a[:, :2]    # Select all rows, first 2 columns (columns 0 and 1)
a[:, 2:]    # Select all rows, columns from index 2 onwards
a[1:3, :]   # Select rows 1 and 2, all columns
a[:, 1:3]   # Select all rows, columns 1 and 2