# Practice Tasks (Do these without looking at the answers)

## Given the tensor above, write the slicing code to:

Print the first 3 rows.
Print the last 2 rows.
Print only the first column.
Print only the last column.
Print the top-left 2×2 block.
Print the bottom-right 2×2 block.
Print every second row.
Print every second column.
Print everything except the first row.
Print everything except the last column

In [10]:
import torch

my_tensor = torch.arange(1,265, dtype=torch.int16)
print(my_tensor)

tensor([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
         15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
         29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
         57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
         71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
         85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
         99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
        127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
        155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 1

In [2]:
print("Print the first 3 rows.")
print(my_tensor[0:3])
print(" \n")

print("Print the last 2 rows.")
print(my_tensor[6:8])
print(" \n")

print("Print only the first column.")
print(my_tensor[0,0])
print(" \n")

print("Print only the last column.")
print(my_tensor[7,7])
print(" \n")

print("Print the top-left 2×2 block.")
print(my_tensor[0:2,0:2])
print(" \n")

print("Print the bottom-right 2×2 block.")
print(my_tensor[6:8,6:8])
print(" \n")

print("Print every second row.")
print(my_tensor[::2])
print(" \n")

print("Print every second column.")
print(my_tensor[:,1])
print(" \n")

print("Print everything except the first row.")
print(my_tensor[1:])
print(" \n")

print("Print everything except the last row.")
print(my_tensor[:7])

Print the first 3 rows.
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]])
 

Print the last 2 rows.
tensor([[49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])
 

Print only the first column.
tensor(1)
 

Print only the last column.
tensor(64)
 

Print the top-left 2×2 block.
tensor([[ 1,  2],
        [ 9, 10]])
 

Print the bottom-right 2×2 block.
tensor([[55, 56],
        [63, 64]])
 

Print every second row.
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [49, 50, 51, 52, 53, 54, 55, 56]])
 

Print every second column.
tensor([ 2, 10, 18, 26, 34, 42, 50, 58])
 

Print everything except the first row.
tensor([[ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 

✅ Tensor creation
✅ Shapes
✅ Indexing
✅ Basic slicing

In [14]:
print(my_tensor.dtype)
my_tensor.numel() * my_tensor.element_size()

torch.int16


528