In [2]:
import torch
print("Gpu enabled: " , torch.cuda.is_available())

Gpu enabled:  True


In [20]:
# Tensors methods

my_tensor = torch.arange(1,10)
my_tensor_1 = torch.randint(10,(2,8,8))
print(my_tensor.reshape(3,3)) # reshape
print(my_tensor.reshape(3,3).flatten()) # flatten into 1d of any dimension

print(my_tensor_1.flatten())
print(my_tensor_1)
print(my_tensor_1.reshape(8,16))



tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([6, 8, 4, 5, 0, 0, 2, 4, 1, 8, 2, 0, 6, 6, 8, 7, 6, 7, 3, 7, 8, 7, 1, 0,
        2, 3, 2, 5, 9, 2, 6, 4, 9, 3, 5, 9, 5, 4, 4, 5, 0, 1, 8, 5, 6, 2, 2, 8,
        9, 9, 4, 9, 2, 2, 7, 3, 1, 4, 4, 9, 8, 2, 5, 9, 7, 9, 7, 1, 4, 0, 0, 9,
        2, 9, 6, 8, 3, 0, 2, 8, 1, 8, 8, 1, 5, 9, 7, 7, 0, 2, 4, 9, 0, 9, 9, 5,
        3, 1, 8, 1, 1, 9, 1, 4, 9, 0, 0, 2, 5, 9, 2, 6, 1, 3, 8, 3, 1, 3, 6, 2,
        3, 6, 1, 9, 6, 2, 9, 0])
tensor([[[6, 8, 4, 5, 0, 0, 2, 4],
         [1, 8, 2, 0, 6, 6, 8, 7],
         [6, 7, 3, 7, 8, 7, 1, 0],
         [2, 3, 2, 5, 9, 2, 6, 4],
         [9, 3, 5, 9, 5, 4, 4, 5],
         [0, 1, 8, 5, 6, 2, 2, 8],
         [9, 9, 4, 9, 2, 2, 7, 3],
         [1, 4, 4, 9, 8, 2, 5, 9]],

        [[7, 9, 7, 1, 4, 0, 0, 9],
         [2, 9, 6, 8, 3, 0, 2, 8],
         [1, 8, 8, 1, 5, 9, 7, 7],
         [0, 2, 4, 9, 0, 9, 9, 5],
         [3, 1, 8, 1, 1, 9, 1, 4],
         [9, 0, 

In [ ]:
print(my_tensor_1.view(-1)) # -1 means pytorch you figure out elements for me its often written as my_tensor.reshape(128)
print(my_tensor_1.flatten())

tensor([6, 8, 4, 5, 0, 0, 2, 4, 1, 8, 2, 0, 6, 6, 8, 7, 6, 7, 3, 7, 8, 7, 1, 0,
        2, 3, 2, 5, 9, 2, 6, 4, 9, 3, 5, 9, 5, 4, 4, 5, 0, 1, 8, 5, 6, 2, 2, 8,
        9, 9, 4, 9, 2, 2, 7, 3, 1, 4, 4, 9, 8, 2, 5, 9, 7, 9, 7, 1, 4, 0, 0, 9,
        2, 9, 6, 8, 3, 0, 2, 8, 1, 8, 8, 1, 5, 9, 7, 7, 0, 2, 4, 9, 0, 9, 9, 5,
        3, 1, 8, 1, 1, 9, 1, 4, 9, 0, 0, 2, 5, 9, 2, 6, 1, 3, 8, 3, 1, 3, 6, 2,
        3, 6, 1, 9, 6, 2, 9, 0])
tensor([6, 8, 4, 5, 0, 0, 2, 4, 1, 8, 2, 0, 6, 6, 8, 7, 6, 7, 3, 7, 8, 7, 1, 0,
        2, 3, 2, 5, 9, 2, 6, 4, 9, 3, 5, 9, 5, 4, 4, 5, 0, 1, 8, 5, 6, 2, 2, 8,
        9, 9, 4, 9, 2, 2, 7, 3, 1, 4, 4, 9, 8, 2, 5, 9, 7, 9, 7, 1, 4, 0, 0, 9,
        2, 9, 6, 8, 3, 0, 2, 8, 1, 8, 8, 1, 5, 9, 7, 7, 0, 2, 4, 9, 0, 9, 9, 5,
        3, 1, 8, 1, 1, 9, 1, 4, 9, 0, 0, 2, 5, 9, 2, 6, 1, 3, 8, 3, 1, 3, 6, 2,
        3, 6, 1, 9, 6, 2, 9, 0])


In [59]:
x = torch.arange(1,10)
# print(x.nelement() * x.element_size())
# print(x.dtype)
print(x.shape)
y = x.unsqueeze(0) # this 0  is position either 0  or 1 , 0 for row and 1 for col
print(y)
print(y.ndim)
print(y.squeeze(0))


torch.Size([9])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
2
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
X = torch.arange(1,19).reshape(1,3,1,3,1,2,1)
X.squeeze() # if no arg removes all one dimensions else only that specific index

TypeError: unsqueeze() missing 1 required positional arguments: "dim"