In [1]:
import torch
print("Gpu enabled: ", torch.cuda.is_available())

Gpu enabled:  True


In [ ]:
# addition
# rule: shape must be same

A = torch.arange(1,5).reshape(2,2)
B = torch.arange(5,9).reshape(2,2)

print(A)
print(B)
print(A + B)
print(torch.add(A,B))

tensor([[ 6,  8],
        [10, 12]])


In [5]:
# subtraction
# rule: shape must be same

print(A)
print(B)
print(A - B)
print(torch.sub(A,B))

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[-4, -4],
        [-4, -4]])


In [ ]:
# multiplication

tensor_a = torch.tensor([[2,2],[4,4]])
tensor_b = torch.tensor([[1,2],[3,4]])

# simple multiplication element-wide
print(tensor_a)
print(tensor_b)

print("Element wise mutiplication")
print(tensor_a * tensor_b)


print("Algebric multiplication")
print(tensor_a @ tensor_b) # OR
print(torch.matmul(tensor_a,tensor_b)) # OR
print(torch.mm(tensor_a,tensor_b)) # all are same




tensor([[2, 2],
        [4, 4]])
tensor([[1, 2],
        [3, 4]])
Element wise mutiplication
tensor([[ 2,  4],
        [12, 16]])
Algebric multiplication
tensor([[ 8, 12],
        [16, 24]])
tensor([[ 8, 12],
        [16, 24]])
tensor([[ 8, 12],
        [16, 24]])


In [12]:
# division
print(A)
print(B)
print(A / B)
print(torch.div(A,B))

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [14]:
# power on matrix (on each element)
print(A ** 2)

tensor([[ 1,  4],
        [ 9, 16]])
