In [1]:
import torch
print("Gpu enabled: ", torch.cuda.is_available())

Gpu enabled:  True


In [ ]:
# broadcasting works in pytorch on arithmetic (element-wise operations) only with few rules.
# 1. move low dimensions shape to the  right side and it should match the left side dimension above it, then remaining left side dimension would become equal to 1 and it can compute the result

# broadcasting only works on element-wise operations.

tensor_1 = torch.randint(1,10, (2,2,3,4))
tensor_2 = torch.randint(1,10, (4,))
print(tensor_1)
print(tensor_2)

print(tensor_1 + tensor_2)

tensor([[[[5, 4, 1, 2],
          [8, 9, 1, 6],
          [3, 7, 9, 5]],

         [[9, 7, 1, 2],
          [5, 9, 4, 4],
          [6, 1, 1, 5]]],


        [[[8, 1, 4, 1],
          [8, 2, 1, 5],
          [6, 9, 2, 9]],

         [[5, 7, 5, 4],
          [5, 9, 4, 4],
          [6, 2, 9, 5]]]])
tensor([6, 4, 9, 8])
tensor([[[[11,  8, 10, 10],
          [14, 13, 10, 14],
          [ 9, 11, 18, 13]],

         [[15, 11, 10, 10],
          [11, 13, 13, 12],
          [12,  5, 10, 13]]],


        [[[14,  5, 13,  9],
          [14,  6, 10, 13],
          [12, 13, 11, 17]],

         [[11, 11, 14, 12],
          [11, 13, 13, 12],
          [12,  6, 18, 13]]]])
