In [1]:
import torch
print(torch.cuda.device_count())

1


In [2]:
# Create a random tensor with shape `(7, 7)`.
TENSOR = torch.rand(7,7)
TENSOR.shape

torch.Size([7, 7])

In [4]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).


TENSOR_1 = torch.Tensor([2])
TENSOR_2 = torch.rand(1,7)


print(TENSOR_1 @ TENSOR_2)


tensor([0.9498, 0.4306, 1.9231, 1.0838, 1.0581, 0.2348, 1.7884])


In [ ]:
# Set the random seed to `0` and do exercises 2 & 3 over again.
SEED=0
torch.random.manual_seed(SEED) # works for both cpu and gpu, in previous versions it donot works for GPU we have to do torch.cuda.manual_seed() 
print(SEED)
RANDOM_TENSOR_1 = torch.rand(3,4, device="cuda")
print(RANDOM_TENSOR_1)
print(SEED)

torch.random.manual_seed(SEED) # we have to manually assign the seed again because the random tensor generator position got updated.
RANDOM_TENSOR_2 = torch.rand(3,4, device="cuda")
print(RANDOM_TENSOR_2)

print(f"Matched:  {RANDOM_TENSOR_1 == RANDOM_TENSOR_2}")


# both are same
# torch.manual_seed(SEED) 
# torch.random.manual_seed(SEED) 


0
tensor([[0.3990, 0.5167, 0.0249, 0.9401],
        [0.9459, 0.7967, 0.4150, 0.8203],
        [0.2290, 0.9096, 0.1183, 0.0752]], device='cuda:0')
0
tensor([[0.3990, 0.5167, 0.0249, 0.9401],
        [0.9459, 0.7967, 0.4150, 0.8203],
        [0.2290, 0.9096, 0.1183, 0.0752]], device='cuda:0')
Matched:  tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]], device='cuda:0')


In [ ]:
torch.manual_seed(1234)

tensor_1 = torch.rand(2,3, device="cuda")
tensor_2 = torch.rand(2,3, device="cuda")

print(tensor_1)
print(tensor_2)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


In [31]:
# tensors multiplication

print(f"Shape: {tensor_1.shape}")
print(f"Shape: {tensor_2.shape}")

# print(tensor_1 @ tensor_2) # results in error because inner dimensions does not match (2,3) X
# print(tensor_1 * tensor_2) # this is element wise multiplication, it will perfectly fine.

y = tensor_1 @ tensor_2.transpose(0,1)
print(y)
# now tensor_2 shapes become: torch.Size([3, 2]) but it is not reassigned or updated to the tensor just on run time



Shape: torch.Size([2, 3])
Shape: torch.Size([2, 3])
tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])


In [34]:
# Find the maximum and minimum values of the output of 7.


print(f" Min: {y.min()}")
print(f'Max: {y.max()}')

# Find the maximum and minimum index values of the output of 7.


print(f"Min Index: {y.argmin()}")
print(f'Max Index: {y.argmax()}')


 Min: 0.3647301495075226
Max: 0.5617256760597229
Min Index: 0
Max Index: 3


In [ ]:
# Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

torch.manual_seed(7)

RANDOM_TENSOR_3 = torch.rand(1,1,1,10)
print(f"RANDOM_TENSOR_3: {RANDOM_TENSOR_3}")
print(f"RANDOM_TENSOR_3 Shape: {RANDOM_TENSOR_3.shape}")

RANDOM_TENSOR_4 = RANDOM_TENSOR_3.squeeze(0,1,2) # also can write only .squeeze() because PyTorch automatically removes all dimensions that are equal to 1.
print(f"RANDOM_TENSOR_4: {RANDOM_TENSOR_4}")
print(f"RANDOM_TENSOR_4 Shape: {RANDOM_TENSOR_4.shape}")




RANDOM_TENSOR_3: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
RANDOM_TENSOR_3 Shape: torch.Size([1, 1, 1, 10])
RANDOM_TENSOR_4: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
RANDOM_TENSOR_4 Shape: torch.Size([10])


Is there any science behind choosing numbers like 42, 7, 1234 as seeds?

Short answer: No, there is no special mathematical power in those numbers.

These are just arbitrary starting points.

People commonly use:

torch.manual_seed(42)
torch.manual_seed(7)
torch.manual_seed(1234)
torch.manual_seed(0)

because they are:

easy to remember
commonly used in tutorials
convenient for reproducing experiments

For example, 42 became popular because of references like The Hitchhiker's Guide to the Galaxy, where 42 is "the answer to life, the universe, and everything."

But scientifically:

torch.manual_seed(42)

is not better than:

torch.manual_seed(918273)
2. How does a seed actually work?

A computer cannot create truly random numbers by itself.

Instead, it uses a pseudo-random number generator.

Think of it like a mathematical machine:

Seed → Algorithm → Random-looking numbers

Example:

Seed = 7

Generator starts here:

7
 |
Algorithm
 |
0.534
 |
Algorithm
 |
0.912
 |
Algorithm
 |
0.221

The numbers look random, but they are actually determined by the seed.

3. Does each digit in the seed have a meaning?

No.

For example:

torch.manual_seed(1234)

does not mean:

1 → controls first dimension
2 → controls second dimension
3 → controls GPU
4 → controls something else

That is not how it works.

The entire number:

1234

is treated as one starting value.

So:

torch.manual_seed(1234)

and:

torch.manual_seed(1235)

start the generator from two completely different positions.

4. Why can a tiny change create completely different results?

Because the seed is fed into a mathematical algorithm.

Example:

Seed 7:

0.534
0.912
0.221
0.876


Seed 8:

0.102
0.654
0.333
0.019

Changing only:

7 → 8

changes the entire sequence.

This is called the avalanche effect.