In [1]:
import torch
print('Gpu enabled: ', torch.cuda.is_available())

Gpu enabled:  True


In [ ]:
# 1.1 Create a 1-D tensor containing the integers 0 through 9. What is its shape and number of dimensions?


vector_1 = torch.arange(0,10)
print(vector_1)
print(vector_1.shape)
print(vector_1.ndim)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([10])
1


In [23]:
# 1.2 A tensor T has shape (4, 3, 2). How many total elements does it contain, and what is its number of dimensions
# (rank)?

TENSOR_1 = torch.randint(1,5,(4,))
print(TENSOR_1)
print(TENSOR_1.nelement())
print(TENSOR_1.ndim)




tensor([4, 2, 1, 1])
4
1


In [21]:
# You create a tensor with torch.zeros(5,5). State its dtype (default) and its shape.
TENSOR_2 = torch.zeros(5,5)
print(TENSOR_2)
print(TENSOR_2.shape)
print(TENSOR_2.dtype)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.Size([5, 5])
torch.float32


In [26]:
# What is the shape of the tensor produced by torch.eye(4)? Describe its values.
TENSOR_3 = torch.eye(4)
print(TENSOR_3)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [28]:
# A tensor is created with torch.arange(2,20,3). List all its elements and give its shape.

TENSOR_4 = torch.arange(2,20,3)
print(TENSOR_4)
print(TENSOR_4.shape)

tensor([ 2,  5,  8, 11, 14, 17])
torch.Size([6])


In [33]:
# torch.linspace(0,1,5) generates 5 evenly spaced values from 0 to 1 inclusive. List them.

TENSOR_5 = torch.linspace(1,3,5, dtype=torch.int16)
print(TENSOR_5)

tensor([1, 1, 2, 2, 3], dtype=torch.int16)


In [ ]:
# What is the difference in output shape between torch.rand(3) and torch.rand(3,1)? State both shapes.
torch.random.manual_seed(45) # i added this seed only for my own practice to see the output is it similar or not.

TENSOR_5 = torch.rand(4)
print(TENSOR_5) # it would be a vector

torch.random.manual_seed(45) # we have to reset the seed again by reassigning it to the same value, every time it generates random tensor the index of seed increases by one means if we didnt done it again so it would be 46

TENSOR_6 = torch.rand(4,1) 
print(TENSOR_6) # it would be a 2d tensor with 4 rows , 1 coloumn


tensor([0.1869, 0.9613, 0.6834, 0.8988])
tensor([[0.1869],
        [0.9613],
        [0.6834],
        [0.8988]])


In [45]:
# Given a tensor x of shape (2, 3, 4), what does x.numel() return?

TENSOR_7 = torch.rand(2,3,4)
print(TENSOR_7)
print(TENSOR_7.numel())
print(TENSOR_7.numel() * TENSOR_7.element_size()) # default dtype is float32, that would be 4 bytes each, after multiplying 4 * 24 it would be 96


tensor([[[0.0917, 0.3388, 0.0747, 0.3002],
         [0.1032, 0.0170, 0.5811, 0.3412],
         [0.2945, 0.3636, 0.3370, 0.1347]],

        [[0.9134, 0.2588, 0.7716, 0.4666],
         [0.0070, 0.5136, 0.4281, 0.8688],
         [0.6318, 0.5512, 0.0155, 0.7184]]])
24
96


In [ ]:
# A tensor x has dtype=torch.float32. After x = x.to(torch.int64), what happens to the value 3.9?

# Ans: the output would become 3 as integer ignore the values after decimal and only consider values before decimal point.

In [46]:
# What tensor does torch.full((2,3), 7) create? Give shape and values.

TENSOR_8 = torch.full((2,3), 7)
print(TENSOR_8)
print(TENSOR_8.shape)

tensor([[7, 7, 7],
        [7, 7, 7]])
torch.Size([2, 3])


In [ ]:
# Explain the difference between torch.tensor(data) and torch.as_tensor(data) when data is already a NumPy array.

# torch.tensor(data) creates a new tensor and copies the data, while torch.as_tensor(data) converts existing data into a tensor and tries to share memory with the original data if possible. Therefore, changes to the original NumPy array may affect the tensor created by as_tensor() but not the tensor created by tensor().

In [ ]:
# What device and requires_grad value does a freshly cre-ated torch.ones(3,3) have by default?

# deviced would be CPU and requires_grad would be false.

In [50]:
X1 = torch.rand(1000,1000,1000, device="cuda")
X2 = torch.rand(1000,1000,1000, device="cuda")

print(X1 @ X2)

tensor([[[261.2996, 262.4837, 261.0635,  ..., 255.2897, 260.8754, 261.9147],
         [252.8401, 246.6301, 253.6042,  ..., 240.4859, 245.0189, 248.1415],
         [243.3162, 250.4059, 247.8282,  ..., 240.4237, 238.4279, 249.1009],
         ...,
         [246.0549, 251.4632, 249.6305,  ..., 245.7996, 245.3562, 248.0404],
         [255.4707, 257.7406, 259.7603,  ..., 252.2092, 256.6355, 259.5763],
         [254.3474, 248.6622, 253.8065,  ..., 246.9633, 251.1302, 261.3377]],

        [[241.8966, 245.4682, 241.1217,  ..., 246.0269, 240.1310, 255.8629],
         [248.4395, 250.1056, 239.2150,  ..., 256.5185, 238.9561, 254.4918],
         [253.7951, 264.0908, 249.3355,  ..., 265.7950, 247.7128, 262.0005],
         ...,
         [242.0553, 252.0639, 247.1290,  ..., 252.8200, 243.6118, 258.2846],
         [248.2018, 249.9003, 247.5098,  ..., 257.0899, 245.9441, 261.5761],
         [254.1733, 261.7300, 252.8272,  ..., 265.1461, 252.3380, 264.5953]],

        [[256.8964, 261.3780, 266.6838,  ...

In [ ]:
X3 = torch.rand(1000,1000,1000)
X4 = torch.rand(1000,1000,1000)

print(X3 @ X4) # these operations are being performed on CPU and above were on GPU just see the time difference

: 

: 

: 

In [ ]:
# Create a tensor of shape (3, 3) filled with values drawn from a standard normal distribution using the function name only (no output needed).
TENSOR_9 = torch.randn(3,3)

In [ ]:
# A tensor x has shape (1, ). Is it a scalar or a 1-D tensor? What is x.item() used for?

# It would return a shape of 1-D tensor. X.item() is used for extracting single element number from tensor and converting it to simple python number.

In [ ]:
# Given x = torch.tensor([1,2,3]) and y = torch.tensor([1.0,2.0 what are x.dtype and y.dtype?

# x dtype = int and y dtype = flo