In [2]:
import torch
import numpy as np
print('Gpu enabled: ', torch.cuda.is_available())

Gpu enabled:  True


In [4]:
# Setup for this chapter’s problems:
A = np.arange(1,25).reshape(4,6)
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
# Given A of shape (4, 6) with values 1 . . . 24 row-major, what is A[0]?

# A[0] would be the first row.

np.int64(1)

In [7]:
# What is A[:, 0]?

# it means first complete row, first coloumn that would be:
# 1

A[:, 0]

array([ 1,  7, 13, 19])

In [8]:
# What is A[1:3, 2:5]?

# Answer
# [ [9, 10, 11]
#   [15, 16, 17] ]

A[1:3, 2:5]

array([[ 9, 10, 11],
       [15, 16, 17]])

In [ ]:
# What is A[-1, -1]?

# answer 
# [24] last row last coloumn

A[-1, -1]

np.int64(24)

In [10]:
# What is A[::2, ::2]?

# [ [1,3,5]
#   [13,15,17] ]

A[::2, ::2]

array([[ 1,  3,  5],
       [13, 15, 17]])

In [14]:
# What is A[:, ::-1]?

A[:, ::1]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [15]:
# What does A[1] return in terms of shape – a row vector or a (1, 6) matrix?

# it would return a row vector
A[1] 

array([ 7,  8,  9, 10, 11, 12])

In [18]:
# What is the shape of A[None, :, :]

A[None, :, :].shape

(1, 4, 6)

In [ ]:
# Given boolean mask mask = A > 12, what does A[mask] return (shape and description)?

mask = A > 12 # compares with every single element
A[mask] # returns only true values ( those which are greater then 12 according to mask condition) and according to the boolean indexing the shape becomes 1 dimensional regardless of any dimension it was, all are flatten to a vector of row.

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
# What is A[[0,2], [1,3]] (advanced/fancy indexing se-lecting two coordinate pairs)?
A[[0,2], [1,3]]

array([ 2, 16])

In [ ]:
# What is the result and shape of A[torch.tensor([0,0,3])] (row gather with repeats)?

A[torch.tensor([0,0,3])] # currently I dont know much about it, its advanced indexing.

array([[ 1,  2,  3,  4,  5,  6],
       [ 1,  2,  3,  4,  5,  6],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
# What happens if you assign A[0, :] = 0? Describe the resulting first row and whether A is modified in place.

A[0, :] = 0 # it will update the orignal tensors first row because it donot creates copy, it is passed by refrence.
A

array([[ 0,  0,  0,  0,  0,  0],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])