In [1]:
import torch
print("Gpu enabled: " , torch.cuda.is_available())

Gpu enabled:  True


# Reduction Operations

In [40]:
TENSOR_1 = torch.randint(1,10,(3,2,3))
TENSOR_1

tensor([[[3, 9, 5],
         [7, 4, 9]],

        [[2, 9, 8],
         [4, 4, 9]],

        [[3, 6, 5],
         [6, 1, 1]]])

In [3]:
# tensor.sum()

print(TENSOR_1)
print(TENSOR_1.sum()) # sum all values of a tensor
print(TENSOR_1.sum(dim=0)) # Sum across rows (vertical). One sum per column.
print(TENSOR_1.sum(dim=1, keepdim=True))   # Sum across columns (horizontal). One sum per row.

# keepdim=True tells PyTorch: "After reducing this dimension, don't remove it. Keep it, but make its size equal to 1."


tensor([[[720, 777, 468],
         [840, 781, 533]],

        [[477, 645, 372],
         [721, 220, 966]],

        [[573, 238, 336],
         [371, 176, 482]]])
tensor(9696)
tensor([[1770, 1660, 1176],
        [1932, 1177, 1981]])
tensor([[[1560, 1558, 1001]],

        [[1198,  865, 1338]],

        [[ 944,  414,  818]]])


In [4]:
# 6.5 What is M.mean()?

TENSOR_1.float().mean()

tensor(538.6667)

In [5]:
# 6.6 What is M.max(dim=1) – give both the values and the indices (argmax) along dim 1?

print(TENSOR_1.max()) # find the largest value
print(TENSOR_1.max(dim=1)) # returns maximum value in each row with its index.

tensor(966)
torch.return_types.max(
values=tensor([[840, 781, 533],
        [721, 645, 966],
        [573, 238, 482]]),
indices=tensor([[1, 1, 1],
        [1, 0, 1],
        [0, 0, 1]]))


In [6]:
# What is M.argmax() on the flattened tensor (single index into the flattened array)?

print(TENSOR_1.reshape(-1).argmax()) # returns the index of the max element in complete tensor.

tensor(11)


In [7]:
# 6.8 What is M.var(dim=0, unbiased=False) (population vari-ance per column)?

print(TENSOR_1.float().mean())
print(TENSOR_1.float().var()) # compare with mean -> the far from mean the spread out values are

tensor(538.6667)
tensor(52943.2930)


In [13]:
# 6.9 What is M.std(dim=0, unbiased=False)?

TENSOR_1.float().std(dim=0, unbiased=False)

tensor([[ 99.9300, 229.3939,  55.7136],
        [199.0594, 275.4153, 217.1395]])

In [32]:
# 6.10 What is M.prod(dim=1) (product along dim 1)?

print(TENSOR_1)
TENSOR_1.prod(dim=0)

tensor([[1, 6, 5],
        [9, 5, 5],
        [6, 2, 8]])


tensor([ 54,  60, 200])

In [35]:
# 6.11 What is M.cumsum(dim=1)?

print(TENSOR_1.shape)
TENSOR_1.cumsum(dim=1)

torch.Size([3, 3])


tensor([[ 1,  7, 12],
        [ 9, 14, 19],
        [ 6,  8, 16]])

In [ ]:
# 6.12 Explain the difference in output shape between M.sum(dim=1) and M.sum(dim=1, keepdim=True).

# keepdim=True keeps the reduced dimension in the output by making its size 1. Without keepdim, the reduced dimension is removed entirely.print(TENSOR_1)

print(TENSOR_1.shape)
print(TENSOR_1.sum(dim=1))
print(TENSOR_1.sum(dim=1).shape)
print(TENSOR_1.sum(dim=1, keepdim=True))
print(TENSOR_1.sum(dim=1, keepdim=True).shape)

tensor([[[3, 9, 5],
         [7, 4, 9]],

        [[2, 9, 8],
         [4, 4, 9]],

        [[3, 6, 5],
         [6, 1, 1]]])
torch.Size([3, 2, 3])
tensor([[10, 13, 14],
        [ 6, 13, 17],
        [ 9,  7,  6]])
torch.Size([3, 3])
tensor([[[10, 13, 14]],

        [[ 6, 13, 17]],

        [[ 9,  7,  6]]])
torch.Size([3, 1, 3])


In [ ]:
# 6.14 What is the result of torch.all(M > 0) and torch.any(M > 5)?

# all = Everyone must pass.
print(TENSOR_1 > 0) # compares with each element and return
print(torch.all(TENSOR_1 > 0)) # wants all elements to match the condition
print(torch.all(TENSOR_1 > 5))

# any = At least one must pass.
print(torch.any(TENSOR_1 > 5))


tensor([[[True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True]]])
tensor(True)
tensor(False)
tensor(True)


In [48]:
# 6.13 What is torch.logsumexp(M, dim=1), and why is it nu-
# merically preferable to computing torch.log(torch.sum(torch.exp(M
# dim=1)) directly?



print(torch.logsumexp(TENSOR_1, dim=1))
# is basically:
print(torch.log(torch.sum(torch.exp(TENSOR_1), dim=1)))

tensor([[7.0181, 9.0067, 9.0182],
        [4.1269, 9.0067, 9.3133],
        [6.0486, 6.0067, 5.0181]])
tensor([[7.0181, 9.0067, 9.0182],
        [4.1269, 9.0067, 9.3133],
        [6.0486, 6.0067, 5.0181]])
