In [1]:
import torch
print("Gpu enabled: " , torch.cuda.is_available())

Gpu enabled:  False


# Reduction Operations

In [37]:
TENSOR_1 = torch.randint(0,1000,(3,2,3))
TENSOR_1

tensor([[[531, 418, 594],
         [556, 659, 165]],

        [[240, 713,  99],
         [688, 818, 630]],

        [[962, 983, 918],
         [559, 618, 285]]])

In [10]:
# tensor.sum()

print(TENSOR_1)
print(TENSOR_1.sum()) # sum all values of a tensor
print(TENSOR_1.sum(dim=0)) # Sum across rows (vertical). One sum per column.
print(TENSOR_1.sum(dim=1, keepdim=True))   # Sum across columns (horizontal). One sum per row.

# keepdim=True tells PyTorch: "After reducing this dimension, don't remove it. Keep it, but make its size equal to 1."


tensor([[8, 0, 9],
        [5, 7, 3]])
tensor(32)
tensor([13,  7, 12])
tensor([[17],
        [15]])


In [12]:
# 6.5 What is M.mean()?

TENSOR_1.float().mean()

tensor(5.3333)

In [ ]:
# 6.6 What is M.max(dim=1) – give both the values and the indices (argmax) along dim 1?

print(TENSOR_1.max()) # find the largest value
print(TENSOR_1.max(dim=1)) # returns maximum value in each row with its index.

tensor(9)
torch.return_types.max(
values=tensor([9, 7]),
indices=tensor([2, 1]))


In [25]:
# What is M.argmax() on the flattened tensor (single index into the flattened array)?

print(TENSOR_1.reshape(-1).argmax()) # returns the index of the max element in complete tensor.

tensor(13)


In [38]:
# 6.8 What is M.var(dim=0, unbiased=False) (population vari-ance per column)?

print(TENSOR_1.float().mean())
print(TENSOR_1.float().var()) # compare with mean -> the far from mean the spread out values are

tensor(579.7778)
tensor(67931.0078)
