In [3]:
import torch
import numpy as np
print("GPU enabled: ", torch.cuda.is_available())

GPU enabled:  True


# Elementwise & Arithmetic Operations

In [38]:
x = torch.tensor([1.0,-2.0,3.0,-4.0])
y = torch.tensor([2.0,2.0,2.0,2.0])

In [9]:
# 5.1 Given a1 = [1, −2, 3, −4], what is a.abs()?


a1 = torch.tensor([1, -2, 3, -4])
a1.abs()

tensor([1, 2, 3, 4])

In [10]:
# 5.2 What is x2 (elementwise square)?

print(x ** 2)

[ 1.  4.  9. 16.]


In [ ]:
# 5.3 What is ReLU(x) = max(x, 0) elementwise?
import torch.nn.functional as F


print(F.relu(x))

# this function keep positive value and convert negative to 0
# --- simple analogy
#     - If positive = keep it
#     - If negative = replace with 0

tensor([1., 0., 3., 0.])


In [16]:
# 5.4 What is torch.sign(x)?

torch.sign(x)

tensor([ 1., -1.,  1., -1.])

In [17]:
# What is x ⊙ y (elementwise product) for a2 = [1, −2, 3, −4], a3 = [2, 2, 2, 2]?

a2 = torch.tensor([1, -2, 3, -4])
a3 = torch.tensor([2, 2, 2, 2])

print(a2 * a3) 


tensor([ 2, -4,  6, -8])


In [18]:
# 5.6 What is x/y elementwise?

print(x/y)


tensor([ 0.5000, -1.0000,  1.5000, -2.0000])


In [21]:
# 5.7 What is torch.clamp(x, min=-1, max=2)?

torch.clamp(x, min=-1, max=3)


tensor([ 1., -1.,  3., -1.])

In [ ]:
# 5.8 What is the sigmoid σ(x) = 1/(1 + e−x ) applied element-wise to x = [1, −2, 3, −4]? Round to 4 decimals.

a4 = torch.tensor([1, -2, 9, -4])
torch.sigmoid(a4) # it map single input value into a smooth number between 0 - 1


tensor([0.7311, 0.1192, 0.9999, 0.0180])

In [ ]:
# 5.9 What is tanh(x) for x = [1, −2, 3, −4]?

torch.tanh(x) # it map single input value into smooth number between -1 and 1.

tensor([ 0.7616, -0.9640,  0.9951, -0.9993])

In [ ]:
# 5.10 What is torch.exp(x) for x = [1, −2, 3, −4]?

torch.exp(x) # exp(x)=e ** x

tensor([2.7183e+00, 1.3534e-01, 2.0086e+01, 1.8316e-02])

In [42]:
# 5.11 Explain the difference between x.add(1) and x.add_(1) in PyTorch.
print(x)
print(x.add(1)) # it creates a new tensor, leaving unchanged the original tensor
print(x.add_(1)) # it updates the existing tensor

tensor([ 4.,  1.,  6., -1.])
tensor([5., 2., 7., 0.])
tensor([5., 2., 7., 0.])


In [43]:
# 5.13 What is x%3 (elementwise modulo) for integer tensor [7, 8, 9, 10]?
print(x)
print(x%3)

tensor([5., 2., 7., 0.])
tensor([2., 2., 1., 0.])


In [ ]:
# 5.14 What is torch.pow(x, 3) for x = [1, −2, 3, −4]?


torch.pow(x, 2) # its power on each element

tensor([25.,  4., 49.,  0.])

In [ ]:
# 5.15 What is the result and dtype of torch.tensor([1,2,3]) / torch.tensor([2,2,2]) in PyTorch (true division vs integer division)?

a6 = torch.tensor([1,2,3]) / torch.tensor([2,2,2])
a6.dtype

IndentationError: unexpected indent (1674574187.py, line 3)