In [1]:
import torch
print("GPU enabled: ", torch.cuda.is_available())

GPU enabled:  True


# Matrix Multiplication & Linear Algebra

In [33]:
A = torch.tensor([[1.,2.],[3.,4.]])
B = torch.tensor([[5.,6.],[7.,8.]])
v = torch.tensor([1.,1.])

print(A)
print(B)
print(v)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])
tensor([1., 1.])


In [3]:
# 7.1 what is A @ B (matrix product)

A @ B

tensor([[19., 22.],
        [43., 50.]])

In [4]:
# 7.2 What is A ⊙ B (elementwise product, NOT matmul)?
A * B

tensor([[ 5., 12.],
        [21., 32.]])

In [ ]:
# 7.3 What is A**T (transpose)?

A.transpose(0,1) # row into coloums OR cols into row.

tensor([[1., 3.],
        [2., 4.]])

In [ ]:
# 7.4 What is A @ v for v = [1, 1]?
print(A.shape)
print(v.shape)

# Matrix multiplication rule:
# (m×n)@(n×p)=(m×p)

A @ v

torch.Size([2, 2])
torch.Size([2])


tensor([3., 7.])

In [ ]:
# 7.5 What is det(A)?

torch.det(A) # formulae of determinant is cross multiply the matrix then subtract.

tensor(-2.)

In [20]:
# 7.6 What is A**−1 ?
print(A)
A.pow(-1)

tensor([[1., 2.],
        [3., 4.]])


tensor([[1.0000, 0.5000],
        [0.3333, 0.2500]])

In [23]:
# 7.7 What is trace(A) (sum of diagonal)?

torch.trace(A)
# torch.trace(A.reshape(-1)) # will not work, it works only on square matrix as diagonals are there

tensor(5.)

In [34]:
# 7.8 Given a batch of matrices X of shape (16, 4, 5) and Y of shape (16, 5, 3), what is the shape of torch.bmm(X, Y)

TENSOR_1 = torch.rand(16,4,5)
TENSOR_2 = torch.rand(16,5,3)

# print("TENSOR_1", TENSOR_1)
# print("TENSOR_2", TENSOR_2)

torch.bmm(TENSOR_1,TENSOR_2) # do matrix multiplcation for 3d tensors

tensor([[[0.6010, 1.6791, 1.7785],
         [0.6940, 1.6974, 1.0329],
         [0.8495, 2.0191, 0.9342],
         [0.8392, 2.1512, 1.0298]],

        [[0.1975, 1.0747, 1.4629],
         [0.6053, 1.3147, 1.2734],
         [0.3584, 1.0841, 1.0341],
         [0.2887, 0.8732, 1.0308]],

        [[1.4534, 1.6634, 2.0739],
         [0.6937, 0.5338, 0.9697],
         [1.1571, 1.0498, 1.0162],
         [0.3668, 0.4472, 0.4618]],

        [[1.0761, 1.2853, 1.6109],
         [1.2614, 1.4553, 1.7030],
         [1.1320, 0.8852, 1.0109],
         [0.8350, 0.8414, 1.1950]],

        [[1.7474, 1.7137, 1.7632],
         [0.9833, 1.7443, 1.1594],
         [0.7655, 0.9669, 0.9281],
         [1.5457, 2.5292, 1.6011]],

        [[1.1884, 1.1216, 0.5030],
         [1.2411, 1.1148, 0.5532],
         [1.4537, 1.4712, 0.7346],
         [1.2256, 1.3824, 0.6123]],

        [[1.2819, 1.7448, 1.6815],
         [1.0705, 1.3954, 1.4322],
         [0.9518, 1.4364, 1.6275],
         [0.3816, 0.7481, 0.6592]],

      

In [ ]:
# Given X of shape (4, 5) and Y of shape (5, 3), what is the shape of X @ Y?

TENSOR_3 = torch.rand(4,5)
TENSOR_4 = torch.rand(5,3)

(TENSOR_3 @ TENSOR_4).shape # (4,3) -> *(m,n) x (n,p) = (m,p)

torch.Size([4, 3])

In [29]:
# 7.10 Given X of shape (2, 4, 5) and a single matrix Y of shape
# (5, 3), what is the shape of X @ Y, and what rule allows
# this without bmm?



TENSOR_5 = torch.rand(2,4,5)
TENSOR_6 = torch.rand(5,3)


(TENSOR_5 @ TENSOR_6).shape # (2,4,3)



torch.Size([2, 4, 3])

In [36]:
# 7.12 For A = , what are its eigenvalues (to 4 decimals)?


print(A)
torch.linalg.eig(A)

tensor([[1., 2.],
        [3., 4.]])


torch.return_types.linalg_eig(
eigenvalues=tensor([-0.3723+0.j,  5.3723+0.j]),
eigenvectors=tensor([[-0.8246+0.j, -0.4160+0.j],
        [ 0.5658+0.j, -0.9094+0.j]]))

In [ ]:
# 7.13 What is the Frobenius norm of A


torch.linalg.norm(A, ord='fro')
# torch.norm(A) # Or simply
